### PR TITLE
Cleanup depsByKey when all dependant entries are disposed

### LINKED ISSUE #497: Dependency keys are not cleared on LRU eviction
Looks like there is a minor "leak" in optimism even with LRU enabled: entries of `depsByKey` always stay in memory even after all optimism `Entries` corresponding to the given key are cleared.

So this `key` + an empty `dep` Set are "leaking":

https://github.com/benjamn/optimism/blob/4301eaca4eee1c29b80a14f65fde8683e4b144fe/src/dep.ts#L31-L35

In my testing it also survives Apollo eviction / GC, even `cache.gc({ resetResultCache: true })`

### PR DESCRIPTION
**Pull request by vladar**
An attempt to clear keys in `depsByKey` when all previously tracked entries are disposed.

With the caveat that we should not call `cleanup` on recompute codepath.

Fixes #497

### CODE REVIEW

**Review by benjamn — APPROVED** [review]
Thanks for diving into this undocumented code and finding a clean, simple solution @vladar!

**Comment by vladar** [comment]
Hey, @benjamn thanks for taking a look. Do you think it will be published as a patch or a minor? Also, when do you plan to publish it?

**Comment by benjamn** [comment]
I've published these changes to npm as `optimism@0.17.0`, or `npm i optimism@next`. I will promote it to `latest` (instead of `next`) after further testing, but I believe it should be usable already.

**Comment by vladar** [comment]
@benjamn, sadly we had to revert this change in our app. Somehow it was causing some watch queries in Apollo not being updated (I assume something is not right with "dirty" codepath).

Still investigating and will follow-up as soon as I have updates. Will also appreciate any thoughts on what could be the culprit there. I suggest to not promote `0.17.0` to `latest` until we find a root cause. I can also open a revert PR if you prefer.

**Comment by benjamn** [comment]
Ok, I'll revert and publish 0.17.1 (also `next`), but I'm happy to keep looking for a solution if you have other ideas.

**Comment by vladar** [comment]
Looks like `dep.cleanup` could be called multiple times for the same empty `dep`. And the problem occurs when another `depend` call happens in between: this call inserts a new set to `depsByKey` at the same key. In this case the second `cleanup` call removes a different set from `depsByKey`.

https://github.com/benjamn/optimism/blob/884d2b67125c106ec6c7ea712b51fc5039f246a2/src/dep.ts#L32-L39

The naive fix would be to do something like this:

```js
   depsByKey.set(key, dep = new Set as Dep<TKey>); 
   dep.cleanup = () => { 
     if (dep.size === 0 && depsByKey.get(key) === dep) { 
       depsByKey.delete(key); 
     } 
   }; 
```
(or maybe alternatively just cleanup once per one Set instance).

This seems to work, but I don't fully understand the sequence of events leading to this weird state, so not a safe bet yet.

**Comment by vladar** [comment]
@benjamn Opened a new (draft) PR with a set of tests that cover the existing leak and several edge case scenarios with cleanup. 

As for the bug that led to the revert - I've found a sequence of events causing the issue. Basically, it requires multiple parents depending on the same key + LRU cache eviction:

```js
const parent1 = wrap((key) => {
  d(key);
  return 1;
}, { max: 1 });

const parent2 = wrap((key) => {
  d(key);
  return 2;
});

parent1("foo"); // Adds a new dep to `depsByKey` and `parent1.deps`.
d.dirty("foo"); // Removes this dep from `depsByKey` (but it still exists in `parent1.deps`).
parent2("foo"); // Adds a new dep to `depsByKey` and `parent2.deps`.
parent1("bar"); // Triggers LRU eviction of parent1 entry with stale "foo" dep,
                //   `cleanup` of this stale "foo" dep incorrectly deletes entry from `depsByKey`
                //   (and thus affects valid `parent2` entry)
```

The new PR has tests for this and several other scenarios. Will appreciate a review: #520

**Pull request merged**
